const Account = require("./index");

describe("Account", () => {
  /** @type {Account} */
  let account,
    /** @type {Object} */
    data,
    /** @type {string} */
    signature;

  beforeEach(() => {
    account = new Account();
    data = {
      foo: "foo",
    };
    signature = account.sign(data);
  });

  describe("verify signature method", () => {
    it("validates a signature generated by the account", () => {
      expect(
        Account.verifySignature({
          publicKey: account.address,
          data,
          signature,
        })
      ).toBe(true);
    });

    it("invalidates a signature not generated by the account", () => {
      expect(
        Account.verifySignature({
          publicKey: new Account().address,
          data,
          signature,
        })
      ).toBe(false);
    });
  });
});
